name: Hide_And_Seek
version: '${project.version}'
main: com.metype.hidenseek.Main
api-version: '1.20'

commands:
  hidenseek:
    aliases: ["hns"]
    description: "The main command for Hide & Seek"

permissions:
  hns.save:
    description: Allows a user to save the current state of all games in the config
    default: op
  hns.reset:
    description: Allows the resetting of config files.
    default: op
  hns.reload:
    description: Allows the reloading of config files.
    default: op
  hns.game.create:
    description: Allows a user to create new games, does not imply the permission hns.game.edit
    default: op
  hns.game.edit:
    description: Allows a user to edit created gamed, does not imply the permission hns.game.create
    default: op
  hns.game.start:
    description: Allows a user to start games.
    default: op
